name = "BankCustomerChurn"
uuid = "44c033a6-4435-4bfa-897b-fdb94e7cba6a"
authors = ["Alicia Key <alicia@alicia.science>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.12.14"
julia = "1.11"
