name = "BankCustomerChurn"
uuid = "44c033a6-4435-4bfa-897b-fdb94e7cba6a"
authors = ["Alicia Key <alicia@alicia.science>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.14"
CairoMakie = "0.12.14"
DataFrames = "1.7.0"
julia = "1.11"
